using System.Net.Security;
const short e = 2;
const int a = 5;
const long d = 10;
const float c = 3;
const double b = 6.4;
const bool f = false;
const char g = '&';
const string h = "hello";
long D = d + a + e;
double B = a + b + c + d + e;
string H = h + " " + g+ " goodbye";
Console.WriteLine(D);
Console.WriteLine(B);
Console.WriteLine(H);
Console.ReadKey();